<template>
    <div class="space-y-4">
        <div class="ios-section pb-4">
            <div class="ios-card p-4 flex items-start justify-between gap-4 flex-wrap">
                <div>
                    <p class="text-sm font-medium text-surface-800 dark:text-surface-100">{{ subject?.display_name ||
                        'No subject selected' }}</p>
                    <p class="text-sm text-surface-500 mt-1">{{ subjectMetaLine }}</p>
                    <p class="text-xs text-surface-400 mt-2">{{ workspaceHint }}</p>
                </div>

                <div class="flex flex-wrap items-center justify-end gap-2">
                    <Button label="Generate DTR" icon="pi pi-file-edit" severity="info" outlined class="rounded"
                        size="small" :disabled="!canOpenGenerateDialog" @click="openGenerateDialog" />
                </div>
            </div>
        </div>

        <div class="ios-section pb-4">
            <p class="ios-section-label">Generated DTR Records</p>
            <div class="ios-card p-4">
                <div v-if="reports.length" class="space-y-3">
                    <div v-for="report in reports" :key="report.id"
                        class="rounded-2xl border border-surface-200 dark:border-surface-800 px-4 py-3 flex items-start justify-between gap-3 flex-wrap">
                        <div>
                            <p class="text-sm font-medium text-surface-800 dark:text-surface-100">
                                {{ formatReportRange(report) }}
                            </p>
                            <p class="text-xs text-surface-400 mt-1">
                                {{ (report.work_days || []).map(formatDayLabel).join(', ') }}
                                <span v-if="report.generated_by_name">· Generated by {{ report.generated_by_name
                                    }}</span>
                            </p>
                        </div>

                        <div class="flex items-center gap-2 flex-wrap">
                            <Button label="Preview" icon="pi pi-eye" severity="secondary" text size="small"
                                :loading="previewingReportId === report.id"
                                :disabled="loadingEditorReportId === report.id || deletingReportId === report.id"
                                @click="openSavedReportPreview(report)" />
                            <Button v-if="canManage" label="Edit" icon="pi pi-pencil" severity="secondary" text
                                size="small" :loading="loadingEditorReportId === report.id"
                                :disabled="isSavingReport || isDeletingReport || previewingReportId === report.id || deletingReportId === report.id"
                                @click="openSavedReportEditor(report)" />
                            <Button v-if="canManage" label="Delete" icon="pi pi-trash" severity="danger" text
                                size="small" :loading="deletingReportId === report.id"
                                :disabled="isSavingReport || isDeletingReport || loadingEditorReportId === report.id || previewingReportId === report.id"
                                @click="deleteSavedReport(report)" />
                            <Tag :value="`${report.day_count} days`" severity="secondary" />
                            <Tag :value="formatCreatedAt(report.created_at)" severity="info" />
                        </div>
                    </div>
                </div>

                <div v-else class="text-center py-8 text-surface-400">
                    <i class="pi pi-calendar-clock text-3xl block mb-3"></i>
                    <p class="text-sm">No DTR records generated yet.</p>
                </div>
            </div>
        </div>

        <Dialog v-model:visible="showGenerateDialog" modal :header="generateDialogTitle" :draggable="false"
            :style="{ width: 'min(auto,96vw)' }">
            <div class="space-y-4">
                <div class="rounded-2xl border border-surface-200 dark:border-surface-800 px-4 py-3">
                    <p class="text-sm font-medium text-surface-800 dark:text-surface-100">{{ subject?.display_name }}
                    </p>
                    <p class="text-xs text-surface-400 mt-1">{{ subjectMetaLine }}</p>
                </div>

                <div v-if="!officeHeads.length"
                    class="rounded-2xl border border-amber-200 bg-amber-50 dark:border-amber-400/20 dark:bg-amber-950/20 p-4">
                    <p class="text-sm font-medium text-amber-900 dark:text-amber-100">No signatory configured</p>
                    <p class="text-sm text-amber-800/80 dark:text-amber-100/80 mt-1">
                        Add at least one Part A office head in Signatories before generating DTR.
                    </p>
                </div>

                <div v-else class="ios-card p-4 flex items-start justify-between gap-4 flex-wrap">
                    <div class="space-y-1 text-sm">
                        <p class="font-medium text-surface-800 dark:text-surface-100" :style="signatoryNameUnderline
                            ? 'display:inline-block;padding-bottom:2px;border-bottom:1px solid currentColor;'
                            : ''">
                            {{ selectedOfficeHead?.name || 'No signatory selected' }}
                        </p>
                        <template v-if="selectedOfficeHead">
                            <p v-for="line in signatoryPreviewLines" :key="line" class="text-surface-500">{{ line }}</p>
                            <p v-if="!signatoryPreviewLines.length" class="text-surface-400">
                                Only the signatory name will appear under Verified and Approved.
                            </p>
                        </template>
                        <p class="text-xs text-surface-400 mt-2">
                            Configure the office head and which titles or designations appear under Verified and
                            Approved.
                        </p>
                    </div>

                    <Button label="Configure Signatory" icon="pi pi-user-edit" class="rounded" size="small"
                        :disabled="!canManage || isSavingReport" @click="showSignatorySnapshotModal = true" />
                </div>

                <div class="ios-card p-4 flex items-start justify-between gap-4 flex-wrap">
                    <p class="text-xs uppercase tracking-[0.2em] text-surface-400 mb-2">Work Schedule</p>

                    <div class="flex flex-wrap gap-2">
                        <button v-for="day in weekdayOptions" :key="day.value" type="button"
                            class="rounded-2xl px-3 py-2 text-sm border transition"
                            :class="generation.work_days.includes(day.value)
                                ? 'border-sky-500 bg-sky-500 text-white'
                                : 'border-surface-200 bg-white text-surface-600 dark:border-surface-700 dark:bg-surface-900 dark:text-surface-300'"
                            :disabled="!canManage || isSavingReport" @click="toggleWorkDay(day.value)">
                            {{ day.label }}
                        </button>
                    </div>
                    <div class="flex flex-wrap gap-4">
                        <FloatLabel variant="on">
                            <label class="ios-label">Start Date</label>
                            <DatePicker v-model="generation.period_start_date" class="w-full" showIcon fluid
                                dateFormat="MM d, yy" :disabled="!canManage || isSavingReport" />
                        </FloatLabel>

                        <FloatLabel variant="on">
                            <label class="ios-label">End Date</label>
                            <DatePicker v-model="generation.period_end_date" class="w-full" showIcon fluid
                                dateFormat="MM d, yy" :disabled="!canManage || isSavingReport" />
                        </FloatLabel>
                    </div>
                </div>

                <div v-if="blockedEventsInRange.length"
                    class="rounded-2xl border border-amber-200 bg-amber-50 dark:border-amber-400/20 dark:bg-amber-950/20 p-4">
                    <p class="text-sm font-medium text-amber-900 dark:text-amber-100">Excluded Calendar Dates</p>
                    <p class="text-sm text-amber-800/80 dark:text-amber-100/80 mt-1">
                        These holiday or suspension dates will be skipped from the DTR draft.
                    </p>
                    <div class="mt-3 flex flex-wrap gap-2">
                        <Tag v-for="event in blockedEventsInRange" :key="`${event.event_date}-${event.title}`"
                            :value="`${formatShortDate(event.event_date)} · ${event.title}`" severity="warn" />
                    </div>
                </div>

                <div v-if="!hasValidScheduleSelection"
                    class="rounded-2xl border border-dashed border-surface-300 dark:border-surface-700 p-5 text-sm text-surface-500">
                    Select the signatory and schedule range to edit daily time values.
                </div>

                <div v-else class="ios-card p-4">
                    <div class="flex items-start justify-between gap-3 flex-wrap mb-3">
                        <div>
                            <p class="text-sm font-medium text-surface-800 dark:text-surface-100">
                                {{ isEditingReport ? 'Edit Saved Time Log' : 'Edit Daily Time Log' }}
                            </p>
                            <p class="text-xs text-surface-400 mt-1">
                                Leave a time blank if it does not apply for that day. Undertime hours/minutes default to
                                0 when empty.
                            </p>
                        </div>

                        <div class="flex items-center gap-2 flex-wrap">
                            <Button v-if="canManage" label="Auto-fill (No Late/Undertime/Absent)" icon="pi pi-bolt"
                                severity="success" outlined size="small" class="rounded"
                                :disabled="!draftDates.length || isSavingReport" v-tooltip.bottom="autoFillTooltip"
                                @click="autoFillRandomHours" />
                            <Tag :value="`${draftDates.length} work day${draftDates.length === 1 ? '' : 's'}`"
                                severity="secondary" />
                        </div>
                    </div>

                    <div v-if="draftDates.length" class="overflow-auto">
                        <table class="min-w-full border-collapse text-xs striped-table">
                            <thead>
                                <tr class="bg-surface-50 dark:bg-surface-900/60">
                                    <th
                                        class="min-w-[100px] border border-surface-200 dark:border-surface-700 px-3 py-2 text-left font-semibold text-surface-700 dark:text-surface-100">
                                        Date
                                    </th>
                                    <th v-for="column in timeColumns" :key="column.field"
                                        class="min-w-[110px] border border-surface-200 dark:border-surface-700 px-3 py-2 text-center font-semibold text-surface-700 dark:text-surface-100">
                                        {{ column.label }}
                                    </th>
                                    <th
                                        class="min-w-[180px] border border-surface-200 dark:border-surface-700 px-3 py-2 text-center font-semibold text-surface-700 dark:text-surface-100">
                                        Travel / OB
                                    </th>
                                </tr>
                            </thead>

                            <tbody>
                                <tr v-for="row in draftValues" :key="row.work_date">
                                    <td
                                        class="border border-surface-200 dark:border-surface-700 px-3 py-2 align-top text-surface-700 dark:text-surface-200">
                                        <p class="font-semibold">{{ formatShortDate(row.work_date) }}</p>
                                        <p class="mt-1 text-[11px] uppercase tracking-[0.14em] text-surface-400">
                                            {{ formatWeekdayLabel(row.work_date) }}
                                        </p>
                                    </td>

                                    <td v-for="column in timeColumns" :key="`${row.work_date}-${column.field}`"
                                        class="border border-surface-200 dark:border-surface-700 px-3 py-2 align-middle text-center">
                                        <input v-if="column.type === 'number'" v-model.number="row[column.field]"
                                            type="number" :min="column.min" :max="column.max"
                                            class="w-full rounded border border-surface-300 bg-white px-2 py-1.5 text-center text-sm text-surface-800 outline-none transition focus:border-sky-500 dark:border-surface-700 dark:bg-surface-950 dark:text-surface-100 disabled:opacity-40"
                                            :disabled="!canManage || isSavingReport || Boolean(row.travel_label)" />
                                        <input v-else v-model="row[column.field]" type="time"
                                            class="w-full rounded border border-surface-300 bg-white px-2 py-1.5 text-center text-sm text-surface-800 outline-none transition focus:border-sky-500 dark:border-surface-700 dark:bg-surface-950 dark:text-surface-100 disabled:opacity-40"
                                            :disabled="!canManage || isSavingReport || Boolean(row.travel_label)" />
                                    </td>

                                    <td
                                        class="border border-surface-200 dark:border-surface-700 px-3 py-2 align-middle text-center">
                                        <input v-model="row.travel_label" type="text" placeholder="e.g. El Nido, Dumaran"
                                            class="w-full rounded border border-surface-300 bg-white px-2 py-1.5 text-center text-sm text-surface-800 outline-none transition focus:border-sky-500 dark:border-surface-700 dark:bg-surface-950 dark:text-surface-100"
                                            :disabled="!canManage || isSavingReport"
                                            v-tooltip.top="'Marks this day as Official Business — consecutive days with the same text merge into one OB row on the DTR.'" />
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>

                    <div v-else
                        class="rounded-2xl border border-dashed border-surface-300 dark:border-surface-700 p-5 text-sm text-surface-500">
                        No work dates were generated for the current schedule. Adjust the date range or selected work
                        days.
                    </div>
                </div>
            </div>

            <template #footer>
                <div class="flex w-full items-center justify-between gap-3 flex-wrap">
                    <p class="text-xs text-surface-400">{{ generateDialogHint }}</p>

                    <div class="flex items-center gap-2 flex-wrap">
                        <Button label="Close" severity="secondary" text @click="closeGenerateDialog" />
                        <Button :label="isEditingReport ? 'Update DTR' : 'Save DTR'"
                            :icon="isEditingReport ? 'pi pi-save' : 'pi pi-check'" class="rounded" size="small"
                            :loading="isSavingReport" :disabled="!canRunGenerateAction" @click="emitSaveReport" />
                    </div>
                </div>
            </template>
        </Dialog>

        <PdfPreviewModal v-model:show="pdfPreview.show" :html-doc="pdfPreview.html" :paper-size="pdfPreview.size"
            :title="pdfPreview.title" />

        <SignatorySnapshotModal v-model:show="showSignatorySnapshotModal" :office-heads="officeHeads"
            :initial-value="dtrSignatorySnapshotForm" modal-title="DTR Signatory" :allow-title-selection="true"
            :allow-display-options="true"
            title-selection-hint="Toggle the titles or designations that should appear under Verified and Approved."
            preview-empty-text="Only the signatory name will appear under Verified and Approved."
            @apply="applyDtrSignatorySnapshot" />
    </div>
</template>

<script setup>
import axios from 'axios';
import dayjs from 'dayjs';
import { usePage } from '@inertiajs/vue3';
import { computed, reactive, ref, watch } from 'vue';
import { useToast } from 'primevue/usetoast';
import { renderVueTemplate, usePdfPrint } from '@/composables/usePdfPrint';
import PdfPreviewModal from '@/Pages/EmployeeFundTransactions/Modal/PdfPreviewModal.vue';
import DtrReportTemplate from '@/Pages/Dtr/Pdf/DtrReportTemplate.vue';
import dtrReportTemplateCss from '@/Pages/Dtr/Pdf/dtr-report-template.css?raw';

const props = defineProps({
    moduleType: { type: String, required: true },
    subject: { type: Object, default: null },
    reports: { type: Array, default: () => [] },
    calendarEvents: { type: Array, default: () => [] },
    officeHeads: { type: Array, default: () => [] },
    canManage: { type: Boolean, default: false },
    isSavingReport: { type: Boolean, default: false },
    isDeletingReport: { type: Boolean, default: false },
});

const emit = defineEmits(['save-report', 'update-report', 'delete-report']);
const page = usePage();
const toast = useToast();
const { buildHtmlDoc } = usePdfPrint();

const weekdayOptions = [
    { label: 'Mon', value: 'monday' },
    { label: 'Tue', value: 'tuesday' },
    { label: 'Wed', value: 'wednesday' },
    { label: 'Thu', value: 'thursday' },
    { label: 'Fri', value: 'friday' },
    { label: 'Sat', value: 'saturday' },
    { label: 'Sun', value: 'sunday' },
];

const timeColumns = [
    { field: 'am_arrival', label: 'AM Arrival', type: 'time' },
    { field: 'am_departure', label: 'AM Departure', type: 'time' },
    { field: 'pm_arrival', label: 'PM Arrival', type: 'time' },
    { field: 'pm_departure', label: 'PM Departure', type: 'time' },
    { field: 'undertime_hours', label: 'Undertime Hrs.', type: 'number', min: 0, max: 23 },
    { field: 'undertime_minutes', label: 'Undertime Mins.', type: 'number', min: 0, max: 59 },
];

// Randomized ranges used by the auto-fill action, each within official hours
// (never late, never undertime, never absent). PM departure depends on the
// work-week length: a compressed 4-day week runs later each day to make up
// the fifth day's hours.
const RANDOM_TIME_RANGES = {
    am_arrival: ['07:00', '08:00'],
    am_departure: ['12:00', '12:29'],
    pm_arrival: ['12:30', '13:00'],
    pm_departure_compressed: ['19:00', '19:30'],
    pm_departure_standard: ['17:00', '17:30'],
};

const showGenerateDialog = ref(false);
const showSignatorySnapshotModal = ref(false);
const previewingReportId = ref(null);
const loadingEditorReportId = ref(null);
const deletingReportId = ref(null);
const draftValues = ref([]);
const editingReportId = ref(null);
const selectedOfficeHeadId = ref(null);
const selectedOfficeHeadTitles = ref([]);
const signatoryNameUnderline = ref(true);
const signatoryShowDesignation = ref(true);
const signatoryShowOffice = ref(true);
const signatoryInfoOrder = ref('designation_first');
const isHydratingReport = ref(false);
const pdfPreview = reactive({
    show: false,
    html: '',
    title: '',
    size: 'a4',
});
const generation = reactive({
    work_days: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
    period_start_date: null,
    period_end_date: null,
});

const canOpenGenerateDialog = computed(() => Boolean(props.subject) && props.canManage);
const isEditingReport = computed(() => editingReportId.value !== null);
const officeHeads = computed(() => props.officeHeads ?? []);
const selectedOfficeHead = computed(() => officeHeads.value.find((officeHead) => officeHead.id === selectedOfficeHeadId.value) ?? null);
const draftDates = computed(() => draftValues.value.map((row) => row.work_date));
const hasValidScheduleSelection = computed(() => Boolean(selectedOfficeHead.value)
    && generation.work_days.length > 0
    && generation.period_start_date
    && generation.period_end_date
    && !dayjs(generation.period_end_date).isBefore(dayjs(generation.period_start_date), 'day'));
const canRunGenerateAction = computed(() => props.canManage
    && !props.isSavingReport
    && hasValidScheduleSelection.value
    && draftDates.value.length > 0);
const generateDialogTitle = computed(() => isEditingReport.value ? 'Update Generated DTR' : 'Generate DTR');
const generateDialogHint = computed(() => {
    if (!officeHeads.value.length) {
        return 'Add at least one Part A office head signatory before generating DTR.';
    }

    if (!selectedOfficeHead.value) {
        return 'Select the signatory that will appear under Verified and Approved.';
    }

    if (!hasValidScheduleSelection.value) {
        return 'Select the schedule range to build the daily time log.';
    }

    return isEditingReport.value
        ? 'Update the time log below, then save your changes.'
        : 'Fill in the time log below, then save to generate the DTR.';
});
const activePmDepartureRange = computed(() => generation.work_days.length === 4
    ? RANDOM_TIME_RANGES.pm_departure_compressed
    : RANDOM_TIME_RANGES.pm_departure_standard);
const autoFillTooltip = computed(() => {
    const [pmDepartureStart, pmDepartureEnd] = activePmDepartureRange.value;

    return `Randomizes each day within official hours — AM Arrival ${formatTimeLabel(RANDOM_TIME_RANGES.am_arrival[0])}-${formatTimeLabel(RANDOM_TIME_RANGES.am_arrival[1])}, `
        + `AM Departure ${formatTimeLabel(RANDOM_TIME_RANGES.am_departure[0])}-${formatTimeLabel(RANDOM_TIME_RANGES.am_departure[1])}, `
        + `PM Arrival ${formatTimeLabel(RANDOM_TIME_RANGES.pm_arrival[0])}-${formatTimeLabel(RANDOM_TIME_RANGES.pm_arrival[1])}, `
        + `PM Departure ${formatTimeLabel(pmDepartureStart)}-${formatTimeLabel(pmDepartureEnd)}`
        + ` (${generation.work_days.length}-day week). Undertime set to 0h 0m.`;
});
const blockedEventsInRange = computed(() => getBlockedEventsInRange(generation.period_start_date, generation.period_end_date));
const blockedDateSet = computed(() => new Set(blockedEventsInRange.value.map((event) => event.event_date)));
const preparedByOffice = computed(() => formatUpperText(props.subject?.office) || 'SCHOLARSHIP PROGRAM');
const preparedByName = computed(() => formatUpperText(props.subject?.display_name) || '______________________________');
const preparedByTitle = computed(() => formatUpperText(props.subject?.designation || props.subject?.secondary_label) || '______________________________');
const reviewerName = computed(() => formatPlainText(selectedOfficeHead.value?.name || page.props.auth?.user?.name) || '______________________________');
const reviewerTitles = computed(() => {
    if (selectedOfficeHead.value) {
        return formatPlainList(selectedOfficeHeadTitles.value);
    }

    const fallbackTitle = formatPlainText(page.props.auth?.user?.designation || page.props.auth?.user?.office_designation) || 'Program Manager';

    return [fallbackTitle];
});
const reviewerOffice = computed(() => formatPlainText(selectedOfficeHead.value?.office || page.props.auth?.user?.office));
const dtrSignatorySnapshotForm = computed(() => ({
    office_head_id: selectedOfficeHeadId.value,
    signatory_titles: [...selectedOfficeHeadTitles.value],
    signatory_name_underline: signatoryNameUnderline.value,
    signatory_show_designation: signatoryShowDesignation.value,
    signatory_show_office: signatoryShowOffice.value,
    signatory_info_order: signatoryInfoOrder.value,
}));
const signatoryPreviewLines = computed(() => buildOrderedSignatoryDetailLines(
    selectedOfficeHeadTitles.value,
    selectedOfficeHead.value?.office,
    signatoryShowDesignation.value,
    signatoryShowOffice.value,
    signatoryInfoOrder.value,
));
const subjectMetaLine = computed(() => {
    if (!props.subject) return 'Select a subject to generate DTR.';

    const parts = [props.subject.employee_no, props.subject.office, props.subject.designation || props.subject.secondary_label]
        .filter(Boolean);

    return parts.join(' · ') || 'DTR subject ready.';
});
const workspaceHint = computed(() => {
    if (!props.subject) return 'Select a subject to generate DTR.';
    if (!props.canManage) return 'Review the generated DTR records here.';

    return 'Generate DTR from the action on the right.';
});

watch(() => props.officeHeads, (nextOfficeHeads) => {
    const availableOfficeHeads = nextOfficeHeads ?? [];

    if (!availableOfficeHeads.length) {
        selectedOfficeHeadId.value = null;
        selectedOfficeHeadTitles.value = [];
        return;
    }

    if (!availableOfficeHeads.some((officeHead) => officeHead.id === selectedOfficeHeadId.value)) {
        applyOfficeHeadSelection(availableOfficeHeads[0].id);
        return;
    }

    const currentOfficeHeadTitles = officeHeadTitlesForId(selectedOfficeHeadId.value);
    selectedOfficeHeadTitles.value = selectedOfficeHeadTitles.value.filter((title) => currentOfficeHeadTitles.includes(title));
}, { immediate: true, deep: true });

watch(() => props.reports?.length ?? 0, (currentCount, previousCount) => {
    if (!showGenerateDialog.value) return;
    if (previousCount == null || currentCount <= previousCount) return;

    showGenerateDialog.value = false;
});

watch(
    [() => generation.work_days.slice(), () => generation.period_start_date, () => generation.period_end_date],
    () => {
        if (isHydratingReport.value || !showGenerateDialog.value) return;

        rebuildDraftValues();
    },
    { deep: true },
);

function openGenerateDialog() {
    if (!canOpenGenerateDialog.value) return;

    resetReportEditState();
    draftValues.value = [];
    showGenerateDialog.value = true;
    rebuildDraftValues();
}

async function openSavedReportEditor(report) {
    if (!props.canManage || props.isSavingReport || props.isDeletingReport) return;

    loadingEditorReportId.value = report.id;

    try {
        const { data } = await axios.get(savedReportEndpoint(report.id));
        const reportDetail = data.data;

        isHydratingReport.value = true;
        editingReportId.value = report.id;
        generation.work_days = [...(reportDetail.work_days ?? [])];
        generation.period_start_date = parseDateValue(reportDetail.period_start_date);
        generation.period_end_date = parseDateValue(reportDetail.period_end_date);
        applyOfficeHeadSelection(reportDetail.office_head_signatory_id, reportDetail.signatory_titles ?? []);
        signatoryNameUnderline.value = reportDetail.signatory_name_underline !== false;
        signatoryShowDesignation.value = reportDetail.signatory_show_designation !== false;
        signatoryShowOffice.value = reportDetail.signatory_show_office !== false;
        signatoryInfoOrder.value = reportDetail.signatory_info_order === 'office_first' ? 'office_first' : 'designation_first';
        draftValues.value = cloneDraftValues(reportDetail.daily_values ?? []);
        showGenerateDialog.value = true;
    } catch (error) {
        resetReportEditState();
        draftValues.value = [];
        toast.add({
            severity: 'error',
            summary: 'Error',
            detail: error.response?.data?.message ?? 'Could not load the saved DTR for editing.',
            life: 4000,
        });
    } finally {
        isHydratingReport.value = false;
        loadingEditorReportId.value = null;
    }
}

function deleteSavedReport(report) {
    if (!props.canManage || props.isSavingReport || props.isDeletingReport) return;

    const confirmed = window.confirm(`Delete the DTR record for ${formatReportRange(report)}?`);

    if (!confirmed) return;

    deletingReportId.value = report.id;
    emit('delete-report', { report_id: report.id }, {
        onSuccess: () => {
            if (editingReportId.value === report.id) {
                closeGenerateDialog();
            }

            deletingReportId.value = null;
        },
        onError: () => {
            deletingReportId.value = null;
        },
    });
}

async function openSavedReportPreview(report) {
    previewingReportId.value = report.id;

    try {
        const { data } = await axios.get(savedReportEndpoint(report.id));
        const reportDetail = data.data;
        const blockedEvents = getBlockedEventsInRange(reportDetail.period_start_date, reportDetail.period_end_date);
        const documentRows = buildDtrDocumentRows(
            reportDetail.period_start_date,
            reportDetail.period_end_date,
            reportDetail.work_days ?? [],
            reportDetail.daily_values ?? [],
            blockedEvents,
        );
        const reportHtml = renderVueTemplate(DtrReportTemplate, {
            documentRows,
            preparedByOffice: preparedByOffice.value,
            preparedByName: preparedByName.value,
            preparedByTitle: preparedByTitle.value,
            reviewerName: formatPlainText(reportDetail.signatory_name) || reviewerName.value,
            reviewerTitles: reportDetail.office_head_signatory_id
                ? formatPlainList(reportDetail.signatory_titles)
                : reviewerTitles.value,
            reviewerOffice: formatPlainText(reportDetail.signatory_office) || reviewerOffice.value,
            reviewerNameUnderline: reportDetail.signatory_name_underline !== false,
            reviewerShowDesignation: reportDetail.signatory_show_designation !== false,
            reviewerShowOffice: reportDetail.signatory_show_office !== false,
            reviewerInfoOrder: reportDetail.signatory_info_order === 'office_first' ? 'office_first' : 'designation_first',
            documentPeriodLabel: formatDtrPeriodLabel(reportDetail.period_start_date, reportDetail.period_end_date),
        });
        const safeName = String(props.subject?.display_name ?? `DTR_${report.id}`).replace(/\s+/g, '_');
        const title = `DTR-${safeName}-${dayjs(reportDetail.period_start_date).format('YYYYMMDD')}`;
        const twoUpHtml = `<div class="dtr-print-sheet"><div class="dtr-card">${reportHtml}</div><div class="dtr-card">${reportHtml}</div></div>`;
        const bodyHtml = `<style>@media screen { body { font-family: Arial, Helvetica, sans-serif; } } @media print { body { padding: 0; font-family: Arial, Helvetica, sans-serif; } } ${dtrReportTemplateCss}</style>${twoUpHtml}`;

        pdfPreview.title = title;
        pdfPreview.size = 'a4';
        pdfPreview.html = buildHtmlDoc(bodyHtml, title, 'a4');
        pdfPreview.show = true;
    } catch (error) {
        toast.add({
            severity: 'error',
            summary: 'Error',
            detail: error.response?.data?.message ?? 'Could not open the saved DTR preview.',
            life: 4000,
        });
    } finally {
        previewingReportId.value = null;
    }
}

function emitSaveReport() {
    if (!canRunGenerateAction.value) return;

    const payload = {
        period_start_date: formatDateForApi(generation.period_start_date),
        period_end_date: formatDateForApi(generation.period_end_date),
        office_head_id: selectedOfficeHeadId.value,
        signatory_titles: [...selectedOfficeHeadTitles.value],
        signatory_name_underline: signatoryNameUnderline.value,
        signatory_show_designation: signatoryShowDesignation.value,
        signatory_show_office: signatoryShowOffice.value,
        signatory_info_order: signatoryInfoOrder.value,
        work_days: [...generation.work_days],
        daily_values: draftValues.value.map((row) => ({
            work_date: row.work_date,
            am_arrival: row.am_arrival || null,
            am_departure: row.am_departure || null,
            pm_arrival: row.pm_arrival || null,
            pm_departure: row.pm_departure || null,
            undertime_hours: Number(row.undertime_hours) || 0,
            undertime_minutes: Number(row.undertime_minutes) || 0,
            travel_label: formatPlainText(row.travel_label) || null,
        })),
    };

    if (isEditingReport.value) {
        emit('update-report', {
            report_id: editingReportId.value,
            ...payload,
        }, {
            onSuccess: () => {
                closeGenerateDialog();
            },
        });

        return;
    }

    emit('save-report', payload);
}

function toggleWorkDay(day) {
    if (!props.canManage || props.isSavingReport) return;

    if (generation.work_days.includes(day)) {
        generation.work_days = generation.work_days.filter((value) => value !== day);
        return;
    }

    generation.work_days = weekdayOptions
        .map((option) => option.value)
        .filter((value) => value === day || generation.work_days.includes(value));
}

function applyDtrSignatorySnapshot(snapshot) {
    applyOfficeHeadSelection(snapshot.office_head_id, snapshot.signatory_titles ?? []);
    signatoryNameUnderline.value = snapshot.signatory_name_underline !== false;
    signatoryShowDesignation.value = snapshot.signatory_show_designation !== false;
    signatoryShowOffice.value = snapshot.signatory_show_office !== false;
    signatoryInfoOrder.value = snapshot.signatory_info_order === 'office_first' ? 'office_first' : 'designation_first';
}

function rebuildDraftValues() {
    if (!hasValidScheduleSelection.value) {
        draftValues.value = [];
        return;
    }

    const workDates = buildWorkDates();
    const existingByDate = new Map(draftValues.value.map((row) => [row.work_date, row]));

    draftValues.value = workDates.map((workDate) => existingByDate.get(workDate) ?? createEmptyDraftRow(workDate));
}

function createEmptyDraftRow(workDate) {
    return {
        work_date: workDate,
        am_arrival: '',
        am_departure: '',
        pm_arrival: '',
        pm_departure: '',
        undertime_hours: 0,
        undertime_minutes: 0,
        travel_label: '',
    };
}

function autoFillRandomHours() {
    if (!props.canManage || props.isSavingReport || !draftValues.value.length) return;

    const [pmDepartureStart, pmDepartureEnd] = activePmDepartureRange.value;

    draftValues.value = draftValues.value.map((row) => (row.travel_label ? row : {
        ...row,
        am_arrival: randomTimeBetween(...RANDOM_TIME_RANGES.am_arrival),
        am_departure: randomTimeBetween(...RANDOM_TIME_RANGES.am_departure),
        pm_arrival: randomTimeBetween(...RANDOM_TIME_RANGES.pm_arrival),
        pm_departure: randomTimeBetween(pmDepartureStart, pmDepartureEnd),
        undertime_hours: 0,
        undertime_minutes: 0,
    }));

    toast.add({
        severity: 'success',
        summary: 'Auto-filled',
        detail: `Randomized ${draftValues.value.length} work day${draftValues.value.length === 1 ? '' : 's'} within official hours, with no undertime.`,
        life: 3000,
    });
}

function randomTimeBetween(startTime, endTime) {
    const toMinutes = (time) => {
        const [hours, minutes] = time.split(':').map(Number);
        return hours * 60 + minutes;
    };

    const startMinutes = toMinutes(startTime);
    const endMinutes = toMinutes(endTime);
    const randomMinutes = startMinutes + Math.floor(Math.random() * (endMinutes - startMinutes + 1));

    const hours = Math.floor(randomMinutes / 60);
    const minutes = randomMinutes % 60;

    return `${String(hours).padStart(2, '0')}:${String(minutes).padStart(2, '0')}`;
}

function buildWorkDates() {
    const start = dayjs(generation.period_start_date);
    const end = dayjs(generation.period_end_date);
    const selectedDays = new Set(generation.work_days);
    const dates = [];
    let cursor = start.startOf('day');

    while (!cursor.isAfter(end, 'day')) {
        const currentDate = cursor.format('YYYY-MM-DD');

        if (selectedDays.has(cursor.format('dddd').toLowerCase()) && !blockedDateSet.value.has(currentDate)) {
            dates.push(currentDate);
        }

        cursor = cursor.add(1, 'day');
    }

    return dates;
}

function cloneDraftValues(rows) {
    return (rows ?? []).map((row) => ({
        work_date: row.work_date,
        am_arrival: row.am_arrival ?? '',
        am_departure: row.am_departure ?? '',
        pm_arrival: row.pm_arrival ?? '',
        pm_departure: row.pm_departure ?? '',
        undertime_hours: row.undertime_hours ?? 0,
        undertime_minutes: row.undertime_minutes ?? 0,
        travel_label: row.travel_label ?? '',
    }));
}

function resetReportEditState() {
    editingReportId.value = null;
}

function closeGenerateDialog() {
    showGenerateDialog.value = false;
    resetReportEditState();
    draftValues.value = [];
}

function officeHeadTitlesForId(officeHeadId) {
    const officeHead = officeHeads.value.find((entry) => entry.id === officeHeadId);
    const titles = Array.isArray(officeHead?.titles) ? officeHead.titles : [];

    return titles
        .map((title) => String(title ?? '').trim())
        .filter(Boolean);
}

function applyOfficeHeadSelection(officeHeadId, selectedTitles = null) {
    const resolvedOfficeHeadId = officeHeads.value.some((entry) => entry.id === officeHeadId)
        ? officeHeadId
        : officeHeads.value[0]?.id ?? null;
    const availableTitles = officeHeadTitlesForId(resolvedOfficeHeadId);

    selectedOfficeHeadId.value = resolvedOfficeHeadId;

    if (!Array.isArray(selectedTitles)) {
        selectedOfficeHeadTitles.value = [...availableTitles];
        return;
    }

    selectedOfficeHeadTitles.value = selectedTitles
        .map((title) => String(title ?? '').trim())
        .filter((title) => availableTitles.includes(title));
}

function buildOrderedSignatoryDetailLines(titles, office, showDesignation = true, showOffice = true, infoOrder = 'designation_first') {
    const designationLines = showDesignation ? formatPlainList(titles) : [];
    const officeLines = showOffice && formatPlainText(office) ? [formatPlainText(office)] : [];

    return uniqueTextLines(infoOrder === 'office_first'
        ? [...officeLines, ...designationLines]
        : [...designationLines, ...officeLines]);
}

function uniqueTextLines(lines) {
    const seen = new Set();

    return (lines ?? [])
        .map((line) => String(line ?? '').trim())
        .filter((line) => {
            if (!line) {
                return false;
            }

            const key = line.toLowerCase();
            if (seen.has(key)) {
                return false;
            }

            seen.add(key);
            return true;
        });
}

function parseDateValue(value) {
    if (!value) return null;

    const parsed = dayjs(value);
    return parsed.isValid() ? parsed.toDate() : null;
}

function getBlockedEventsInRange(startValue, endValue) {
    if (!startValue || !endValue) return [];

    const start = dayjs(startValue).startOf('day');
    const end = dayjs(endValue).endOf('day');

    return (props.calendarEvents ?? [])
        .filter((event) => {
            const eventDate = dayjs(event.event_date);
            return eventDate.isValid() && !eventDate.isBefore(start, 'day') && !eventDate.isAfter(end, 'day');
        })
        .sort((left, right) => left.event_date.localeCompare(right.event_date));
}

function buildDtrDocumentRows(startValue, endValue, workDays, rows, blockedEvents = []) {
    if (!startValue || !endValue) return [];

    const selectedDays = new Set((workDays ?? []).map((day) => String(day).toLowerCase()));
    const blockedEventMap = new Map(blockedEvents.map((event) => [event.event_date, event]));
    const valuesByDate = new Map((rows ?? []).map((row) => [row.work_date, row]));
    const documentRows = [];
    let cursor = dayjs(startValue).startOf('day');
    const end = dayjs(endValue).startOf('day');

    while (!cursor.isAfter(end, 'day')) {
        const workDate = cursor.format('YYYY-MM-DD');
        const weekday = cursor.format('dddd').toLowerCase();
        const blockedEvent = blockedEventMap.get(workDate);

        if (blockedEvent) {
            documentRows.push({
                key: `special-${workDate}`,
                kind: blockedEvent.event_type === 'work_suspension' ? 'work_suspension' : 'special',
                day_number: cursor.date(),
                label: blockedEvent.event_type === 'work_suspension' ? 'WORK SUSPENSION' : 'HOLIDAY',
            });
            cursor = cursor.add(1, 'day');
            continue;
        }

        if (!selectedDays.has(weekday)) {
            documentRows.push({
                key: `special-${workDate}`,
                kind: 'offday',
                day_number: cursor.date(),
                label: cursor.format('dddd').toUpperCase(),
            });
            cursor = cursor.add(1, 'day');
            continue;
        }

        const travelLabel = formatPlainText(valuesByDate.get(workDate)?.travel_label);

        if (travelLabel) {
            const runCursors = [cursor];
            let next = cursor.add(1, 'day');

            // Extend the run while adjacent days are still scheduled work days
            // carrying the exact same travel note — each keeps its own day row,
            // only the note cell merges (rowspan) across the run.
            while (!next.isAfter(end, 'day')) {
                const nextDate = next.format('YYYY-MM-DD');
                const nextWeekday = next.format('dddd').toLowerCase();

                if (blockedEventMap.has(nextDate) || !selectedDays.has(nextWeekday)) break;
                if (formatPlainText(valuesByDate.get(nextDate)?.travel_label) !== travelLabel) break;

                runCursors.push(next);
                next = next.add(1, 'day');
            }

            runCursors.forEach((dayCursor, index) => {
                documentRows.push({
                    key: `travel-${dayCursor.format('YYYY-MM-DD')}`,
                    kind: 'travel',
                    day_number: dayCursor.date(),
                    label: index === 0 ? `OB - ${travelLabel}` : null,
                    rowspan: index === 0 ? runCursors.length : null,
                    merged: index !== 0,
                });
            });

            cursor = runCursors[runCursors.length - 1].add(1, 'day');
            continue;
        }

        documentRows.push({
            key: `work-${workDate}`,
            kind: 'work',
            day_number: cursor.date(),
            values: valuesByDate.get(workDate) ?? createEmptyDraftRow(workDate),
        });

        cursor = cursor.add(1, 'day');
    }

    return documentRows;
}

function formatDateForApi(value) {
    return value ? dayjs(value).format('YYYY-MM-DD') : '';
}

function formatShortDate(value) {
    return dayjs(value).format('MMM D');
}

function formatWeekdayLabel(value) {
    return dayjs(value).format('ddd').toUpperCase();
}

function formatTimeLabel(value) {
    return dayjs(`2000-01-01T${value}`).format('h:mm A');
}

function formatDtrPeriodLabel(startValue, endValue) {
    if (!startValue || !endValue) return '—';

    const start = dayjs(startValue);
    const end = dayjs(endValue);

    if (!start.isValid() || !end.isValid()) return '—';

    if (start.year() === end.year()) {
        if (start.month() === end.month()) {
            return `${start.format('MMMM').toUpperCase()} ${start.date()}-${end.date()}, ${end.format('YYYY')}`;
        }

        return `${start.format('MMMM').toUpperCase()} ${start.date()}-${end.format('MMMM').toUpperCase()} ${end.date()}, ${end.format('YYYY')}`;
    }

    return `${start.format('MMMM').toUpperCase()} ${start.date()}, ${start.format('YYYY')} - ${end.format('MMMM').toUpperCase()} ${end.date()}, ${end.format('YYYY')}`;
}

function formatUpperText(value) {
    const text = String(value ?? '').trim();
    return text ? text.toUpperCase() : '';
}

function formatUpperList(values) {
    return (Array.isArray(values) ? values : [])
        .map((value) => formatUpperText(value))
        .filter(Boolean);
}

function formatPlainText(value) {
    return String(value ?? '').trim();
}

function formatPlainList(values) {
    return (Array.isArray(values) ? values : [])
        .map((value) => formatPlainText(value))
        .filter(Boolean);
}

function formatDayLabel(value) {
    const match = weekdayOptions.find((option) => option.value === value);
    return match?.label ?? value;
}

function formatReportRange(report) {
    return `${dayjs(report.period_start_date).format('MMM D, YYYY')} - ${dayjs(report.period_end_date).format('MMM D, YYYY')}`;
}

function formatCreatedAt(value) {
    return value ? dayjs(value).format('MMM D, YYYY h:mm A') : 'Saved';
}

function savedReportEndpoint(reportId) {
    if (props.moduleType === 'personal') {
        return `/api/dtr/personal/reports/${reportId}`;
    }

    return `/api/dtr/employees/${props.subject?.id}/reports/${reportId}`;
}
</script>
