<template>
    <div class="space-y-4">
        <div class="ios-section pb-4">
            <div class="ios-card p-4 flex items-start justify-between gap-4 flex-wrap">
                <div>
                    <p class="text-sm font-medium text-surface-800 dark:text-surface-100">{{ subject?.display_name ||
                        'No subject selected' }}</p>
                    <p class="text-sm text-surface-500 mt-1">{{ subjectMetaLine }}</p>
                    <div class="flex justify-between items-center gap-4 mt-2">
                        <p class="text-xs text-surface-400 mt-2">{{ workspaceHint }}
                        </p>
                        <Tag :value="`${completedTaskCount}/5 tasks`"
                            :severity="completedTaskCount === 5 ? 'success' : 'warning'" />
                    </div>
                </div>

                <div class="flex flex-wrap items-center justify-end gap-2">
                    <Button label="Task Encoding" icon="pi pi-list-check" severity="success" outlined class="rounded"
                        size="small" :disabled="!subject" @click="openTaskDialog" />
                    <Button label="Generate SWA" icon="pi pi-file-edit" severity="info" outlined class="rounded"
                        size="small" :disabled="!canOpenGenerateDialog" @click="openGenerateDialog" />
                    <!-- <Tag :value="moduleTag" severity="info" /> -->

                </div>
            </div>
        </div>

        <div class="ios-section pb-4">
            <p class="ios-section-label">Generated SWA Records</p>
            <div class="ios-card p-4">
                <p class="text-xs text-surface-400 mb-3">
                    Task encoding and SWA generation open in dialogs so this workspace stays focused on saved records.
                </p>

                <div v-if="reports.length" class="space-y-3">
                    <div v-for="report in reports" :key="report.id"
                        class="rounded-2xl border border-surface-200 dark:border-surface-800 px-4 py-3 flex items-start justify-between gap-3 flex-wrap">
                        <div>
                            <p class="text-sm font-medium text-surface-800 dark:text-surface-100">
                                {{ formatReportRange(report) }}
                            </p>
                            <p class="text-xs text-surface-400 mt-1">
                                {{ (report.work_days || []).map(formatDayLabel).join(', ') }}
                                <span v-if="report.generated_by_name">· Generated by {{ report.generated_by_name
                                }}</span>
                            </p>
                        </div>

                        <div class="flex items-center gap-2 flex-wrap">
                            <Button label="Preview" icon="pi pi-eye" severity="secondary" text size="small"
                                :loading="previewingReportId === report.id"
                                :disabled="loadingEditorReportId === report.id || deletingReportId === report.id"
                                @click="openSavedReportPreview(report)" />
                            <Button v-if="canManage" label="Edit" icon="pi pi-pencil" severity="secondary" text
                                size="small" :loading="loadingEditorReportId === report.id"
                                :disabled="isSavingReport || isDeletingReport || previewingReportId === report.id || deletingReportId === report.id"
                                @click="openSavedReportEditor(report)" />
                            <Button v-if="canManage" label="Delete" icon="pi pi-trash" severity="danger" text
                                size="small" :loading="deletingReportId === report.id"
                                :disabled="isSavingReport || isDeletingReport || loadingEditorReportId === report.id || previewingReportId === report.id"
                                @click="deleteSavedReport(report)" />
                            <Tag :value="`${report.task_count} tasks`" severity="secondary" />
                            <Tag :value="formatCreatedAt(report.created_at)" severity="info" />
                        </div>
                    </div>
                </div>

                <div v-else class="text-center py-8 text-surface-400">
                    <i class="pi pi-calendar-clock text-3xl block mb-3"></i>
                    <p class="text-sm">No SWA records generated yet.</p>
                </div>
            </div>
        </div>

        <Dialog v-model:visible="showTaskDialog" modal header="Task Encoding" :draggable="false"
            :style="{ width: 'min(920px, 96vw)' }">
            <div class="space-y-4">
                <div class="rounded-2xl border border-surface-200 dark:border-surface-800 px-4 py-3">
                    <p class="text-sm font-medium text-surface-800 dark:text-surface-100">{{ subject?.display_name }}
                    </p>
                    <p class="text-xs text-surface-400 mt-1">{{ subjectMetaLine }}</p>
                </div>

                <div class="flex items-center justify-between gap-3 flex-wrap">
                    <div>
                        <p class="text-sm font-medium text-surface-800 dark:text-surface-100">Five active tasks</p>
                        <p class="text-xs text-surface-400 mt-1">
                            Exactly 5 tasks are required for each subject. Task type can be countable or check/blank
                            (-). Min and max values for countable auto-generation are stored on this device only.
                        </p>
                    </div>

                    <div class="flex items-center gap-3">
                        <span class="text-sm text-surface-500">{{ taskDialogModeLabel }}</span>
                        <ToggleSwitch v-model="taskEditMode"
                            :disabled="!canManage || isSavingTasks || isSavingReport" />
                    </div>
                </div>

                <div v-if="!canManage"
                    class="rounded-2xl border border-surface-200 dark:border-surface-800 bg-surface-50 dark:bg-surface-900/80 p-4 text-sm text-surface-500">
                    You have read-only access to task encoding for this subject.
                </div>

                <div v-else-if="!taskEditMode"
                    class="rounded-2xl border border-sky-200 bg-sky-50 dark:border-sky-400/20 dark:bg-sky-950/20 p-4 text-sm text-sky-900 dark:text-sky-100">
                    Switch to edit mode to update task names and task types.
                </div>

                <div class="space-y-3">
                    <div v-for="row in taskRows" :key="row.sort_order"
                        class="grid gap-3 md:grid-cols-[auto_minmax(0,1fr)_220px] items-start">
                        <Tag :value="`Task ${row.sort_order}`" severity="secondary" />

                        <div class="ios-form-group">
                            <InputText v-model="row.task_name" class="w-full" placeholder="Enter task description"
                                :disabled="!canEditTasks" />
                        </div>

                        <div class="ios-form-group">
                            <Select v-model="row.task_type" :options="taskTypeOptions" optionLabel="label"
                                optionValue="value" class="w-full" :disabled="!canEditTasks" />
                        </div>

                        <div v-if="row.task_type === 'countable'"
                            class="md:col-start-2 md:col-span-2 grid gap-3 md:grid-cols-2">
                            <div class="ios-form-group">
                                <label class="ios-label">Auto Min Value</label>
                                <InputNumber v-model="row.auto_min" class="xs:w-full w-1/8"
                                    inputClass="w-full text-right" placeholder="Minimum" :useGrouping="false" :min="0"
                                    :minFractionDigits="0" :maxFractionDigits="0" :disabled="!canEditTasks" />
                            </div>

                            <div class="ios-form-group">
                                <label class="ios-label">Auto Max Value</label>
                                <InputNumber v-model="row.auto_max" class="xs:w-full w-1/8"
                                    inputClass="w-full text-right" placeholder="Maximum" :useGrouping="false" :min="0"
                                    :minFractionDigits="0" :maxFractionDigits="0" :disabled="!canEditTasks" />
                            </div>

                            <p class="md:col-span-2 text-xs"
                                :class="isCountableRangeInvalid(row) ? 'text-rose-500' : 'text-surface-400'">
                                {{ isCountableRangeInvalid(row)
                                    ? 'Enter a valid range where max is greater than or equal to min.'
                                    : 'These bounds are used only when the draft preview auto-generates countable values.'
                                }}
                            </p>
                        </div>
                    </div>
                </div>
            </div>

            <template #footer>
                <div class="flex w-full items-center justify-between gap-3 flex-wrap">
                    <p class="text-xs text-surface-400">{{ completedTaskCount }}/5 tasks ready</p>

                    <div class="flex items-center gap-2">
                        <Button label="Close" severity="secondary" text @click="showTaskDialog = false" />
                        <Button v-if="canManage" label="Save Tasks" icon="pi pi-save" class="rounded" size="small"
                            :loading="isSavingTasks" :disabled="!taskEditMode || !hasValidTasks || isSavingReport"
                            @click="emitSaveTasks" />
                    </div>
                </div>
            </template>
        </Dialog>

        <Dialog v-model:visible="showGenerateDialog" modal :header="generateDialogTitle" :draggable="false"
            :style="{ width: 'min(auto,96vw)' }">
            <div class="space-y-4">
                <div class="rounded-2xl border border-surface-200 dark:border-surface-800 px-4 py-3">
                    <div class="flex items-start justify-between gap-3 flex-wrap">
                        <div>
                            <p class="text-sm font-medium text-surface-800 dark:text-surface-100">{{
                                subject?.display_name }}
                            </p>
                            <p class="text-xs text-surface-400 mt-1">{{ subjectMetaLine }}</p>
                        </div>

                        <Tag :value="`${completedTaskCount}/5 tasks ready`"
                            :severity="completedTaskCount === 5 ? 'success' : 'warning'" />
                    </div>
                </div>

                <div v-if="!officeHeads.length"
                    class="rounded-2xl border border-amber-200 bg-amber-50 dark:border-amber-400/20 dark:bg-amber-950/20 p-4">
                    <p class="text-sm font-medium text-amber-900 dark:text-amber-100">No signatory configured</p>
                    <p class="text-sm text-amber-800/80 dark:text-amber-100/80 mt-1">
                        Add at least one Part A office head in Signatories before generating SWA.
                    </p>
                </div>

                <div v-else class="ios-card p-4 flex items-start justify-between gap-4 flex-wrap">
                    <div class="space-y-1 text-sm">
                        <p class="font-medium text-surface-800 dark:text-surface-100"
                            :style="signatoryNameUnderline
                                ? 'display:inline-block;padding-bottom:2px;border-bottom:1px solid currentColor;'
                                : ''">
                            {{ selectedOfficeHead?.name || 'No signatory selected' }}
                        </p>
                        <template v-if="selectedOfficeHead">
                            <p v-for="line in signatoryPreviewLines" :key="line" class="text-surface-500">{{ line }}</p>
                            <p v-if="!signatoryPreviewLines.length" class="text-surface-400">
                                Only the signatory name will appear under Verified and Approved.
                            </p>
                        </template>
                        <p class="text-xs text-surface-400 mt-2">
                            Configure the office head and which titles or designations appear under Verified and
                            Approved.
                        </p>
                    </div>

                    <Button label="Configure Signatory" icon="pi pi-user-edit" class="rounded" size="small"
                        :disabled="!canManage || isSavingReport || isSavingTasks"
                        @click="showSignatorySnapshotModal = true" />
                </div>

                <div class="ios-card  p-4 flex items-start justify-between gap-4 flex-wrap">
                    <p class="text-xs uppercase tracking-[0.2em] text-surface-400 mb-2">Work Schedule</p>

                    <div class="flex flex-wrap gap-2">
                        <button v-for="day in weekdayOptions" :key="day.value" type="button"
                            class="rounded-2xl px-3 py-2 text-sm border transition"
                            :class="generation.work_days.includes(day.value)
                                ? 'border-sky-500 bg-sky-500 text-white'
                                : 'border-surface-200 bg-white text-surface-600 dark:border-surface-700 dark:bg-surface-900 dark:text-surface-300'"
                            :disabled="!canManage || isSavingReport || isSavingTasks" @click="toggleWorkDay(day.value)">
                            {{ day.label }}
                        </button>
                    </div>
                    <div class="flex flex-wrap gap-4">
                        <FloatLabel variant="on">
                            <label class="ios-label">Start Date</label>
                            <DatePicker v-model="generation.period_start_date" class="w-full" showIcon fluid
                                dateFormat="MM d, yy" :disabled="!canManage || isSavingReport || isSavingTasks" />
                        </FloatLabel>


                        <FloatLabel variant="on">
                            <label class="ios-label">End Date</label>
                            <DatePicker v-model="generation.period_end_date" class="w-full" showIcon fluid
                                dateFormat="MM d, yy" :disabled="!canManage || isSavingReport || isSavingTasks" />
                        </FloatLabel>
                    </div>
                </div>



                <div v-if="blockedEventsInRange.length"
                    class="rounded-2xl border border-amber-200 bg-amber-50 dark:border-amber-400/20 dark:bg-amber-950/20 p-4">
                    <p class="text-sm font-medium text-amber-900 dark:text-amber-100">Excluded Calendar Dates</p>
                    <p class="text-sm text-amber-800/80 dark:text-amber-100/80 mt-1">
                        These holiday or suspension dates will be skipped from the SWA draft.
                    </p>
                    <div class="mt-3 flex flex-wrap gap-2">
                        <Tag v-for="event in blockedEventsInRange" :key="`${event.event_date}-${event.title}`"
                            :value="`${formatShortDate(event.event_date)} · ${event.title}`" severity="warn" />
                    </div>
                </div>

                <div v-if="!draftRows.length"
                    class="rounded-2xl border border-dashed border-surface-300 dark:border-surface-700 p-5 text-sm text-surface-500">
                    Select the schedule range, then use the primary action below to edit daily values.
                </div>

                <div v-if="draftRows.length" class="ios-card p-4">
                    <div class="flex items-start justify-between gap-3 flex-wrap mb-3">
                        <div>
                            <p class="text-sm font-medium text-surface-800 dark:text-surface-100">
                                {{ isEditingReport ? 'Edit Saved Daily Values' : 'Edit Generated Daily Values' }}
                            </p>
                            <p class="text-xs text-surface-400 mt-1">
                                Tasks are columns and dates are rows. Use the Preview action on saved records when you
                                need the printable SWA layout.
                            </p>
                        </div>

                        <div class="flex items-center gap-2 flex-wrap">
                            <Button v-if="canManage" label="Rebuild Daily Values" icon="pi pi-refresh" severity="info"
                                size="small" :disabled="!canPrepareDraft || isSavingReport || isSavingTasks"
                                @click="rebuildDraftValues" v-tooltip.bottom="'Click to Randomized Daily Values'" />
                            <Tag :value="`${draftDates.length} work day${draftDates.length === 1 ? '' : 's'}`"
                                severity="secondary" />
                        </div>
                    </div>

                    <div v-if="draftEditorRows.length" class="overflow-auto">
                        <table class="min-w-full border-collapse text-xs striped-table">
                            <thead>
                                <tr class="bg-surface-50 dark:bg-surface-900/60">
                                    <th
                                        class="min-w-[110px] border border-surface-200 dark:border-surface-700 px-3 py-2 text-left font-semibold text-surface-700 dark:text-surface-100">
                                        Date
                                    </th>
                                    <th v-for="task in draftRows" :key="task.sort_order"
                                        class="min-w-[140px] border border-surface-200 dark:border-surface-700 px-3 py-4 text-left align-top">
                                        <p class="font-semibold text-surface-800 dark:text-surface-100 text-[10px]">
                                            Task {{ task.sort_order }}
                                        </p>
                                        <p
                                            class="mt-1 text-surface-600 dark:text-surface-300 whitespace-normal break-words text-[11px]">
                                            {{ task.task_name }}
                                        </p>
                                        <!-- <p class="mt-1 text-[11px] uppercase tracking-[0.14em] text-surface-400">
                                            {{ formatTaskType(task.task_type) }}
                                        </p> -->
                                    </th>
                                </tr>
                            </thead>

                            <tbody>
                                <tr v-for="editorRow in draftEditorRows" :key="editorRow.work_date">
                                    <td
                                        class="border border-surface-200 dark:border-surface-700 px-3 py-2 align-top text-surface-700 dark:text-surface-200">
                                        <p class="font-semibold">{{ formatShortDate(editorRow.work_date) }}</p>
                                        <p class="mt-1 text-[11px] uppercase tracking-[0.14em] text-surface-400">
                                            {{ formatWeekdayLabel(editorRow.work_date) }}
                                        </p>
                                    </td>

                                    <td v-for="taskValue in editorRow.task_values"
                                        :key="`${editorRow.work_date}-${taskValue.sort_order}`"
                                        class="border border-surface-200 dark:border-surface-700 px-3 py-2 align-middle items-center justify-center">
                                        <input v-if="taskValue.task_type === 'countable'"
                                            v-model.number="taskValue.cell.numeric_value" v-keyfilter.int type="text"
                                            class="w-1/3 justify-center rounded border border-surface-300 bg-white px-3 py-2 text-right text-sm text-surface-800 outline-none transition focus:border-sky-500 dark:border-surface-700 dark:bg-surface-950 dark:text-surface-100 cursor-pointer"
                                            :disabled="!canManage || isSavingReport" />

                                        <button v-else type="button"
                                            class="w-1/3 justify-center rounded border  px-3 py-2  text-sm font-semibold transition cursor-pointer"
                                            :class="taskValue.cell.mark_value === 'check'
                                                ? 'border-emerald-500 text-emerald-600'
                                                : 'border-surface-300 bg-white text-surface-500 dark:border-surface-700 dark:bg-surface-950 dark:text-surface-300'"
                                            :disabled="!canManage || isSavingReport"
                                            @click="toggleMarkValue(taskValue.cell)">
                                            {{ taskValue.cell.mark_value === 'check' ? '✓' : '-' }}
                                        </button>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>

                    <div v-else
                        class="rounded-2xl border border-dashed border-surface-300 dark:border-surface-700 p-5 text-sm text-surface-500">
                        No work dates were generated for the current schedule. Adjust the date range or selected work
                        days, then edit or rebuild the daily values.
                    </div>
                </div>
            </div>

            <template #footer>
                <div class="flex w-full items-center justify-between gap-3 flex-wrap">
                    <p class="text-xs text-surface-400">{{ generateDialogHint }}</p>

                    <div class="flex items-center gap-2 flex-wrap">
                        <Button label="Close" severity="secondary" text @click="closeGenerateDialog" />
                        <Button :label="generateActionLabel" :icon="generateActionIcon" class="rounded" size="small"
                            :loading="isSavingReport" :disabled="!canRunGenerateAction" @click="runGenerateAction" />
                    </div>
                </div>
            </template>
        </Dialog>

        <PdfPreviewModal v-model:show="pdfPreview.show" :html-doc="pdfPreview.html" :paper-size="pdfPreview.size"
            :title="pdfPreview.title" />

        <SignatorySnapshotModal v-model:show="showSignatorySnapshotModal" :office-heads="officeHeads"
            :initial-value="swaSignatorySnapshotForm" modal-title="SWA Signatory" :allow-title-selection="true"
            :allow-display-options="true"
            title-selection-hint="Toggle the titles or designations that should appear under Verified and Approved."
            preview-empty-text="Only the signatory name will appear under Verified and Approved."
            @apply="applySwaSignatorySnapshot" />
    </div>
</template>

<script setup>
import axios from 'axios';
import dayjs from 'dayjs';
import { usePage } from '@inertiajs/vue3';
import { computed, reactive, ref, watch } from 'vue';
import { useToast } from 'primevue/usetoast';
import { renderVueTemplate, usePdfPrint } from '@/composables/usePdfPrint';
import PdfPreviewModal from '@/Pages/EmployeeFundTransactions/Modal/PdfPreviewModal.vue';
import SwaReportTemplate from '@/Pages/Swa/Pdf/SwaReportTemplate.vue';
import swaReportTemplateCss from '@/Pages/Swa/Pdf/swa-report-template.css?raw';

const props = defineProps({
    moduleType: { type: String, required: true },
    subject: { type: Object, default: null },
    tasks: { type: Array, default: () => [] },
    reports: { type: Array, default: () => [] },
    calendarEvents: { type: Array, default: () => [] },
    officeHeads: { type: Array, default: () => [] },
    canManage: { type: Boolean, default: false },
    isSavingTasks: { type: Boolean, default: false },
    isSavingReport: { type: Boolean, default: false },
    isDeletingReport: { type: Boolean, default: false },
});

const emit = defineEmits(['save-tasks', 'save-report', 'update-report', 'delete-report']);
const page = usePage();
const toast = useToast();
const { buildHtmlDoc } = usePdfPrint();

const weekdayOptions = [
    { label: 'Mon', value: 'monday' },
    { label: 'Tue', value: 'tuesday' },
    { label: 'Wed', value: 'wednesday' },
    { label: 'Thu', value: 'thursday' },
    { label: 'Fri', value: 'friday' },
    { label: 'Sat', value: 'saturday' },
    { label: 'Sun', value: 'sunday' },
];

const taskTypeOptions = [
    { label: 'Countable', value: 'countable' },
    { label: 'Check / Blank (-)', value: 'check_blank' },
];

const DEFAULT_COUNTABLE_MIN = 1;
const DEFAULT_COUNTABLE_MAX = 9;

const showTaskDialog = ref(false);
const showGenerateDialog = ref(false);
const showSignatorySnapshotModal = ref(false);
const previewingReportId = ref(null);
const loadingEditorReportId = ref(null);
const deletingReportId = ref(null);
const taskEditMode = ref(false);
const taskRows = ref(createEmptyTaskRows());
const draftRows = ref([]);
const draftDates = ref([]);
const editingReportId = ref(null);
const editingReportTaskRows = ref([]);
const selectedOfficeHeadId = ref(null);
const selectedOfficeHeadTitles = ref([]);
const signatoryNameUnderline = ref(true);
const signatoryShowDesignation = ref(true);
const signatoryShowOffice = ref(true);
const signatoryInfoOrder = ref('designation_first');
const isHydratingReport = ref(false);
const pdfPreview = reactive({
    show: false,
    html: '',
    title: '',
    size: 'a4',
});
const generation = reactive({
    work_days: ['monday', 'tuesday', 'wednesday', 'thursday'],
    period_start_date: null,
    period_end_date: null,
});

const moduleTag = computed(() => props.moduleType === 'personal' ? 'Personal' : 'Employee');
const completedTaskCount = computed(() => normalizedTasks.value.filter((task) => task.task_name).length);
const hasValidTasks = computed(() => completedTaskCount.value === 5);
const hasValidCountableRanges = computed(() => taskRows.value.every((row) => !isCountableRangeInvalid(row)));
const canEditTasks = computed(() => props.canManage && taskEditMode.value && !props.isSavingTasks && !props.isSavingReport);
const canOpenGenerateDialog = computed(() => Boolean(props.subject) && props.canManage && hasValidTasks.value);
const hasDraftPreview = computed(() => draftRows.value.length > 0);
const hasDraftEditorValues = computed(() => hasDraftPreview.value && draftDates.value.length > 0);
const isEditingReport = computed(() => editingReportId.value !== null);
const officeHeads = computed(() => props.officeHeads ?? []);
const selectedOfficeHead = computed(() => officeHeads.value.find((officeHead) => officeHead.id === selectedOfficeHeadId.value) ?? null);
const draftSourceRows = computed(() => isEditingReport.value && editingReportTaskRows.value.length
    ? editingReportTaskRows.value
    : normalizedTasks.value);
const hasValidDraftSourceTasks = computed(() => draftSourceRows.value.filter((task) => task.task_name).length === 5);
const hasValidScheduleSelection = computed(() => Boolean(selectedOfficeHead.value)
    && generation.work_days.length > 0
    && generation.period_start_date
    && generation.period_end_date
    && !dayjs(generation.period_end_date).isBefore(dayjs(generation.period_start_date), 'day'));
const canEditDraftValues = computed(() => props.canManage
    && hasValidDraftSourceTasks.value
    && hasValidScheduleSelection.value);
const canPrepareDraft = computed(() => canEditDraftValues.value
    && (isEditingReport.value || hasValidCountableRanges.value));
const canRunGenerateAction = computed(() => {
    if (!props.canManage || props.isSavingTasks || props.isSavingReport) return false;

    if (hasDraftEditorValues.value) {
        return canEditDraftValues.value;
    }

    return isEditingReport.value ? canEditDraftValues.value : canPrepareDraft.value;
});
const taskDialogModeLabel = computed(() => {
    if (!props.canManage) return 'Read only';

    return taskEditMode.value ? 'Edit mode' : 'Read only';
});
const generateDialogTitle = computed(() => isEditingReport.value ? 'Update Generated SWA' : 'Generate SWA');
const generateActionLabel = computed(() => {
    if (!hasDraftEditorValues.value) return isEditingReport.value ? 'Edit Daily Values' : 'Prepare Daily Values';

    return isEditingReport.value ? 'Update SWA' : 'Save SWA';
});
const generateActionIcon = computed(() => {
    if (!hasDraftEditorValues.value) return isEditingReport.value ? 'pi pi-pencil' : 'pi pi-table';

    return isEditingReport.value ? 'pi pi-save' : 'pi pi-check';
});
const generateDialogHint = computed(() => {
    if (!officeHeads.value.length) {
        return 'Add at least one Part A office head signatory before generating SWA.';
    }

    if (!selectedOfficeHead.value) {
        return 'Select the signatory that will appear under Verified and Approved.';
    }

    if (!isEditingReport.value && !hasValidCountableRanges.value) {
        return 'Each countable task needs a valid min and max range before the daily values can be prepared.';
    }

    if (hasDraftEditorValues.value) {
        return isEditingReport.value
            ? 'The saved daily values are editable below. Rebuild them only when you want a fresh randomized table.'
            : 'The generated daily values are editable below. Save when everything looks correct.';
    }

    return isEditingReport.value
        ? 'Open the daily values table first. Existing values stay in place unless you rebuild them.'
        : 'Prepare the daily values table first, then review and save the SWA.';
});
const blockedEventsInRange = computed(() => getBlockedEventsInRange(generation.period_start_date, generation.period_end_date));
const blockedDateSet = computed(() => new Set(blockedEventsInRange.value.map((event) => event.event_date)));
const preparedByOffice = computed(() => formatUpperText(props.subject?.office) || 'SCHOLARSHIP PROGRAM');
const preparedByName = computed(() => formatUpperText(props.subject?.display_name) || '______________________________');
const preparedByTitle = computed(() => formatUpperText(props.subject?.designation || props.subject?.secondary_label) || '______________________________');
const reviewerName = computed(() => formatUpperText(selectedOfficeHead.value?.name || page.props.auth?.user?.name) || '______________________________');
const reviewerTitles = computed(() => {
    if (selectedOfficeHead.value) {
        return formatUpperList(selectedOfficeHeadTitles.value);
    }

    const fallbackTitle = formatUpperText(page.props.auth?.user?.designation || page.props.auth?.user?.office_designation) || 'PROGRAM MANAGER';

    return [fallbackTitle];
});
const reviewerOffice = computed(() => formatUpperText(selectedOfficeHead.value?.office || page.props.auth?.user?.office));
const reviewerDetailLines = computed(() => buildOrderedSignatoryDetailLines(
    reviewerTitles.value,
    reviewerOffice.value,
    signatoryShowDesignation.value,
    signatoryShowOffice.value,
    signatoryInfoOrder.value,
));
const documentPeriodLabel = computed(() => formatSwaPeriodLabel(generation.period_start_date, generation.period_end_date));
const swaSignatorySnapshotForm = computed(() => ({
    office_head_id: selectedOfficeHeadId.value,
    signatory_titles: [...selectedOfficeHeadTitles.value],
    signatory_name_underline: signatoryNameUnderline.value,
    signatory_show_designation: signatoryShowDesignation.value,
    signatory_show_office: signatoryShowOffice.value,
    signatory_info_order: signatoryInfoOrder.value,
}));
const signatoryPreviewLines = computed(() => buildOrderedSignatoryDetailLines(
    selectedOfficeHeadTitles.value,
    selectedOfficeHead.value?.office,
    signatoryShowDesignation.value,
    signatoryShowOffice.value,
    signatoryInfoOrder.value,
));
const draftEditorRows = computed(() => draftDates.value.map((workDate) => ({
    work_date: workDate,
    task_values: draftRows.value.map((task) => ({
        sort_order: task.sort_order,
        task_type: task.task_type,
        cell: findDraftCell(task, workDate),
    })),
})));
const normalizedTasks = computed(() => taskRows.value.map((row) => ({
    sort_order: row.sort_order,
    task_name: String(row.task_name ?? '').trim(),
    task_type: row.task_type,
})));
const subjectMetaLine = computed(() => {
    if (!props.subject) return 'Select a subject to encode tasks and generate SWA.';

    const parts = [props.subject.employee_no, props.subject.office, props.subject.designation || props.subject.secondary_label]
        .filter(Boolean);

    return parts.join(' · ') || 'SWA subject ready.';
});
const workspaceHint = computed(() => {
    if (!props.subject) return 'Select a subject to open task encoding and SWA generation.';
    if (!props.canManage) return 'Review task encoding from the dialog and monitor the generated SWA records here.';
    if (!hasValidTasks.value) return 'Complete the five-task encoding to enable SWA generation.';

    return 'Open task encoding or generate SWA from the actions on the right.';
});

watch(() => props.tasks, (tasks) => {
    const persistedRanges = loadCountableRangeSettings();

    taskRows.value = createEmptyTaskRows(persistedRanges);

    (tasks ?? []).forEach((task) => {
        const index = Math.max(0, Math.min(4, Number(task.sort_order ?? 1) - 1));
        taskRows.value[index] = {
            ...createTaskRow(index + 1, persistedRanges[index + 1]),
            task_name: task.task_name ?? '',
            task_type: task.task_type ?? 'countable',
        };
    });
}, { immediate: true, deep: true });

watch(taskRows, () => {
    persistCountableRangeSettings();
}, { deep: true });

watch(() => props.officeHeads, (nextOfficeHeads) => {
    const availableOfficeHeads = nextOfficeHeads ?? [];

    if (!availableOfficeHeads.length) {
        selectedOfficeHeadId.value = null;
        selectedOfficeHeadTitles.value = [];
        return;
    }

    if (!availableOfficeHeads.some((officeHead) => officeHead.id === selectedOfficeHeadId.value)) {
        applyOfficeHeadSelection(availableOfficeHeads[0].id);
        return;
    }

    const currentOfficeHeadTitles = officeHeadTitlesForId(selectedOfficeHeadId.value);
    selectedOfficeHeadTitles.value = selectedOfficeHeadTitles.value.filter((title) => currentOfficeHeadTitles.includes(title));
}, { immediate: true, deep: true });

watch(() => props.reports?.length ?? 0, (currentCount, previousCount) => {
    if (!showGenerateDialog.value) return;
    if (previousCount == null || currentCount <= previousCount) return;

    showGenerateDialog.value = false;
});

watch(
    [taskRows, () => generation.work_days.slice(), () => generation.period_start_date, () => generation.period_end_date],
    () => {
        if (isHydratingReport.value || !hasDraftPreview.value || !canEditDraftValues.value) return;

        editDraftValues();
    },
    { deep: true },
);

function openTaskDialog() {
    if (!props.subject) return;

    taskEditMode.value = props.canManage && !hasValidTasks.value;
    showTaskDialog.value = true;
}

function openGenerateDialog() {
    if (!canOpenGenerateDialog.value) return;

    resetReportEditState();
    clearDraftPreview();
    showGenerateDialog.value = true;
}

async function openSavedReportEditor(report) {
    if (!props.canManage || props.isSavingReport || props.isDeletingReport) return;

    loadingEditorReportId.value = report.id;

    try {
        const { data } = await axios.get(savedReportEndpoint(report.id));
        const reportDetail = data.data;
        const reportRows = cloneDraftRows(reportDetail.draft_rows ?? []);

        isHydratingReport.value = true;
        editingReportId.value = report.id;
        editingReportTaskRows.value = reportRows.map((row) => ({
            sort_order: row.sort_order,
            task_name: row.task_name,
            task_type: row.task_type,
        }));
        generation.work_days = [...(reportDetail.work_days ?? [])];
        generation.period_start_date = parseDateValue(reportDetail.period_start_date);
        generation.period_end_date = parseDateValue(reportDetail.period_end_date);
        applyOfficeHeadSelection(reportDetail.office_head_signatory_id, reportDetail.signatory_titles ?? []);
        signatoryNameUnderline.value = reportDetail.signatory_name_underline !== false;
        signatoryShowDesignation.value = reportDetail.signatory_show_designation !== false;
        signatoryShowOffice.value = reportDetail.signatory_show_office !== false;
        signatoryInfoOrder.value = reportDetail.signatory_info_order === 'office_first' ? 'office_first' : 'designation_first';
        draftRows.value = reportRows;
        draftDates.value = reportRows[0]?.daily_values?.map((value) => value.work_date) ?? [];
        showGenerateDialog.value = true;
    } catch (error) {
        resetReportEditState();
        clearDraftPreview();
        toast.add({
            severity: 'error',
            summary: 'Error',
            detail: error.response?.data?.message ?? 'Could not load the saved SWA for editing.',
            life: 4000,
        });
    } finally {
        isHydratingReport.value = false;
        loadingEditorReportId.value = null;
    }
}

function deleteSavedReport(report) {
    if (!props.canManage || props.isSavingReport || props.isDeletingReport) return;

    const confirmed = window.confirm(`Delete the SWA record for ${formatReportRange(report)}?`);

    if (!confirmed) return;

    deletingReportId.value = report.id;
    emit('delete-report', { report_id: report.id }, {
        onSuccess: () => {
            if (editingReportId.value === report.id) {
                closeGenerateDialog();
            }

            deletingReportId.value = null;
        },
        onError: () => {
            deletingReportId.value = null;
        },
    });
}

async function openSavedReportPreview(report) {
    previewingReportId.value = report.id;

    try {
        const { data } = await axios.get(savedReportEndpoint(report.id));
        const reportDetail = data.data;
        const reportRows = reportDetail.draft_rows ?? [];
        const blockedEvents = getBlockedEventsInRange(reportDetail.period_start_date, reportDetail.period_end_date);
        const documentRows = buildSwaDocumentRows(
            reportDetail.period_start_date,
            reportDetail.period_end_date,
            reportDetail.work_days ?? [],
            reportRows,
            blockedEvents,
        );
        const reportHtml = renderVueTemplate(SwaReportTemplate, {
            draftRows: reportRows,
            documentRows,
            preparedByOffice: preparedByOffice.value,
            preparedByName: preparedByName.value,
            preparedByTitle: preparedByTitle.value,
            reviewerName: formatUpperText(reportDetail.signatory_name) || reviewerName.value,
            reviewerTitles: reportDetail.office_head_signatory_id
                ? formatUpperList(reportDetail.signatory_titles)
                : reviewerTitles.value,
            reviewerOffice: formatUpperText(reportDetail.signatory_office) || reviewerOffice.value,
            reviewerNameUnderline: reportDetail.signatory_name_underline !== false,
            reviewerShowDesignation: reportDetail.signatory_show_designation !== false,
            reviewerShowOffice: reportDetail.signatory_show_office !== false,
            reviewerInfoOrder: reportDetail.signatory_info_order === 'office_first' ? 'office_first' : 'designation_first',
            documentPeriodLabel: formatSwaPeriodLabel(reportDetail.period_start_date, reportDetail.period_end_date),
            editable: false,
            canManage: false,
            isSavingReport: true,
        });
        const safeName = String(props.subject?.display_name ?? `SWA_${report.id}`).replace(/\s+/g, '_');
        const title = `SWA-${safeName}-${dayjs(reportDetail.period_start_date).format('YYYYMMDD')}`;
        const bodyHtml = `<style>@page { margin: 8mm 8mm; } @media screen { body { padding: 8mm 8mm; font-family: Arial, Helvetica, sans-serif; } } @media print { body { padding: 0; font-family: Arial, Helvetica, sans-serif; } } ${swaReportTemplateCss}</style>${reportHtml}`;

        pdfPreview.title = title;
        pdfPreview.size = 'a4';
        pdfPreview.html = buildHtmlDoc(bodyHtml, title, 'a4');
        pdfPreview.show = true;
    } catch (error) {
        toast.add({
            severity: 'error',
            summary: 'Error',
            detail: error.response?.data?.message ?? 'Could not open the saved SWA preview.',
            life: 4000,
        });
    } finally {
        previewingReportId.value = null;
    }
}

function runGenerateAction() {
    if (!canRunGenerateAction.value) return;

    if (!hasDraftEditorValues.value) {
        if (isEditingReport.value) {
            editDraftValues();
            return;
        }

        prepareDraftValues();
        return;
    }

    emitSaveReport();
}

function emitSaveTasks() {
    emit('save-tasks', normalizedTasks.value);
}

function emitSaveReport() {
    const payload = {
        tasks: normalizedTasks.value,
        period_start_date: formatDateForApi(generation.period_start_date),
        period_end_date: formatDateForApi(generation.period_end_date),
        office_head_id: selectedOfficeHeadId.value,
        signatory_titles: [...selectedOfficeHeadTitles.value],
        signatory_name_underline: signatoryNameUnderline.value,
        signatory_show_designation: signatoryShowDesignation.value,
        signatory_show_office: signatoryShowOffice.value,
        signatory_info_order: signatoryInfoOrder.value,
        work_days: [...generation.work_days],
        draft_rows: draftRows.value.map((row) => ({
            sort_order: row.sort_order,
            daily_values: row.daily_values.map((value) => ({
                work_date: value.work_date,
                numeric_value: row.task_type === 'countable' ? Number(value.numeric_value ?? 0) : null,
                mark_value: row.task_type === 'check_blank' ? value.mark_value : null,
            })),
        })),
    };

    if (isEditingReport.value) {
        emit('update-report', {
            report_id: editingReportId.value,
            ...payload,
            tasks: undefined,
        }, {
            onSuccess: () => {
                closeGenerateDialog();
            },
        });

        return;
    }

    emit('save-report', payload);
}

function toggleWorkDay(day) {
    if (!props.canManage || props.isSavingTasks || props.isSavingReport) return;

    if (generation.work_days.includes(day)) {
        generation.work_days = generation.work_days.filter((value) => value !== day);
        return;
    }

    generation.work_days = weekdayOptions
        .map((option) => option.value)
        .filter((value) => value === day || generation.work_days.includes(value));
}

function applySwaSignatorySnapshot(snapshot) {
    applyOfficeHeadSelection(snapshot.office_head_id, snapshot.signatory_titles ?? []);
    signatoryNameUnderline.value = snapshot.signatory_name_underline !== false;
    signatoryShowDesignation.value = snapshot.signatory_show_designation !== false;
    signatoryShowOffice.value = snapshot.signatory_show_office !== false;
    signatoryInfoOrder.value = snapshot.signatory_info_order === 'office_first' ? 'office_first' : 'designation_first';
}

function prepareDraftValues() {
    if (!canPrepareDraft.value) return;

    const workDates = buildWorkDates();
    const sourceRows = draftSourceRows.value;

    draftDates.value = workDates;
    draftRows.value = sourceRows.map((task) => ({
        sort_order: task.sort_order,
        task_name: String(task.task_name ?? '').trim(),
        task_type: task.task_type,
        daily_values: workDates.map((workDate) => ({
            work_date: workDate,
            numeric_value: task.task_type === 'countable' ? randomCountableValue(task) : null,
            mark_value: task.task_type === 'check_blank' ? randomMarkValue() : null,
        })),
    }));
}

function editDraftValues() {
    if (!canEditDraftValues.value) return;

    const workDates = buildWorkDates();
    const sourceRows = draftSourceRows.value;
    const currentDraftRows = new Map(draftRows.value.map((row) => [row.sort_order, row]));

    draftDates.value = workDates;
    draftRows.value = sourceRows.map((task) => {
        const existingRow = currentDraftRows.get(task.sort_order);
        const shouldPreserveValues = existingRow?.task_type === task.task_type;
        const existingValues = new Map((shouldPreserveValues ? existingRow?.daily_values : []).map((value) => [value.work_date, value]));

        return {
            sort_order: task.sort_order,
            task_name: String(task.task_name ?? '').trim(),
            task_type: task.task_type,
            daily_values: workDates.map((workDate) => {
                const existingValue = existingValues.get(workDate);

                return {
                    work_date: workDate,
                    numeric_value: task.task_type === 'countable'
                        ? Number(existingValue?.numeric_value ?? 0)
                        : null,
                    mark_value: task.task_type === 'check_blank'
                        ? (existingValue?.mark_value === 'check' ? 'check' : 'dash')
                        : null,
                };
            }),
        };
    });
}

function rebuildDraftValues() {
    if (!canPrepareDraft.value) return;

    prepareDraftValues();
}

function buildWorkDates() {
    const start = dayjs(generation.period_start_date);
    const end = dayjs(generation.period_end_date);
    const selectedDays = new Set(generation.work_days);
    const dates = [];
    let cursor = start.startOf('day');

    while (!cursor.isAfter(end, 'day')) {
        const currentDate = cursor.format('YYYY-MM-DD');

        if (selectedDays.has(cursor.format('dddd').toLowerCase()) && !blockedDateSet.value.has(currentDate)) {
            dates.push(currentDate);
        }

        cursor = cursor.add(1, 'day');
    }

    return dates;
}

function toggleMarkValue(cell) {
    if (!props.canManage || props.isSavingReport) return;

    cell.mark_value = cell.mark_value === 'check' ? 'dash' : 'check';
}

function findDraftCell(task, workDate) {
    return task.daily_values.find((value) => value.work_date === workDate) ?? {
        work_date: workDate,
        numeric_value: task.task_type === 'countable' ? 0 : null,
        mark_value: task.task_type === 'check_blank' ? 'dash' : null,
    };
}

function createEmptyTaskRows(persistedRanges = {}) {
    return Array.from({ length: 5 }, (_, index) => createTaskRow(index + 1, persistedRanges[index + 1]));
}

function clearDraftPreview() {
    draftRows.value = [];
    draftDates.value = [];
}

function resetReportEditState() {
    editingReportId.value = null;
    editingReportTaskRows.value = [];
}

function closeGenerateDialog() {
    showGenerateDialog.value = false;
    resetReportEditState();
    clearDraftPreview();
}

function officeHeadTitlesForId(officeHeadId) {
    const officeHead = officeHeads.value.find((entry) => entry.id === officeHeadId);
    const titles = Array.isArray(officeHead?.titles) ? officeHead.titles : [];

    return titles
        .map((title) => String(title ?? '').trim())
        .filter(Boolean);
}

function applyOfficeHeadSelection(officeHeadId, selectedTitles = null) {
    const resolvedOfficeHeadId = officeHeads.value.some((entry) => entry.id === officeHeadId)
        ? officeHeadId
        : officeHeads.value[0]?.id ?? null;
    const availableTitles = officeHeadTitlesForId(resolvedOfficeHeadId);

    selectedOfficeHeadId.value = resolvedOfficeHeadId;

    if (!Array.isArray(selectedTitles)) {
        selectedOfficeHeadTitles.value = [...availableTitles];
        return;
    }

    selectedOfficeHeadTitles.value = selectedTitles
        .map((title) => String(title ?? '').trim())
        .filter((title) => availableTitles.includes(title));
}

function buildSwaSignatoryPreviewLines(officeHead, selectedTitles) {
    return buildOrderedSignatoryDetailLines(
        selectedTitles,
        officeHead?.office,
        signatoryShowDesignation.value,
        signatoryShowOffice.value,
        signatoryInfoOrder.value,
    );
}

function buildOrderedSignatoryDetailLines(titles, office, showDesignation = true, showOffice = true, infoOrder = 'designation_first') {
    const designationLines = showDesignation ? formatUpperList(titles) : [];
    const officeLines = showOffice && formatUpperText(office) ? [formatUpperText(office)] : [];

    return uniqueTextLines(infoOrder === 'office_first'
        ? [...officeLines, ...designationLines]
        : [...designationLines, ...officeLines]);
}

function uniqueTextLines(lines) {
    const seen = new Set();

    return (lines ?? [])
        .map((line) => String(line ?? '').trim())
        .filter((line) => {
            if (!line) {
                return false;
            }

            const key = line.toLowerCase();
            if (seen.has(key)) {
                return false;
            }

            seen.add(key);
            return true;
        });
}

function cloneDraftRows(rows) {
    return (rows ?? []).map((row) => ({
        sort_order: row.sort_order,
        task_name: row.task_name,
        task_type: row.task_type,
        daily_values: (row.daily_values ?? []).map((value) => ({
            work_date: value.work_date,
            numeric_value: value.numeric_value,
            mark_value: value.mark_value,
        })),
    }));
}

function parseDateValue(value) {
    if (!value) return null;

    const parsed = dayjs(value);
    return parsed.isValid() ? parsed.toDate() : null;
}

function createTaskRow(sortOrder, persistedRange = {}) {
    return {
        sort_order: sortOrder,
        task_name: '',
        task_type: 'countable',
        auto_min: normalizeStoredRangeValue(persistedRange.min, DEFAULT_COUNTABLE_MIN),
        auto_max: normalizeStoredRangeValue(persistedRange.max, DEFAULT_COUNTABLE_MAX),
    };
}

function normalizeStoredRangeValue(value, fallback) {
    const numericValue = Number(value);

    if (!Number.isFinite(numericValue)) return fallback;

    return Math.max(0, Math.trunc(numericValue));
}

function loadCountableRangeSettings() {
    const storageKey = getCountableRangeStorageKey();

    if (!storageKey || typeof window === 'undefined') return {};

    try {
        return JSON.parse(window.localStorage.getItem(storageKey) ?? '{}');
    } catch {
        return {};
    }
}

function getBlockedEventsInRange(startValue, endValue) {
    if (!startValue || !endValue) return [];

    const start = dayjs(startValue).startOf('day');
    const end = dayjs(endValue).endOf('day');

    return (props.calendarEvents ?? [])
        .filter((event) => {
            const eventDate = dayjs(event.event_date);
            return eventDate.isValid() && !eventDate.isBefore(start, 'day') && !eventDate.isAfter(end, 'day');
        })
        .sort((left, right) => left.event_date.localeCompare(right.event_date));
}

function buildSwaDocumentRows(startValue, endValue, workDays, rows, blockedEvents = []) {
    if (!startValue || !endValue || !rows.length) return [];

    const selectedDays = new Set((workDays ?? []).map((day) => String(day).toLowerCase()));
    const blockedEventMap = new Map(blockedEvents.map((event) => [event.event_date, event]));
    const documentRows = [];
    let cursor = dayjs(startValue).startOf('day');
    const end = dayjs(endValue).startOf('day');

    while (!cursor.isAfter(end, 'day')) {
        const workDate = cursor.format('YYYY-MM-DD');
        const weekday = cursor.format('dddd').toLowerCase();
        const blockedEvent = blockedEventMap.get(workDate);

        if (blockedEvent) {
            documentRows.push({
                key: `special-${workDate}`,
                kind: blockedEvent.event_type === 'work_suspension' ? 'work_suspension' : 'special',
                day_number: cursor.date(),
                label: blockedEvent.event_type === 'work_suspension' ? 'WORK SUSPENSION' : 'HOLIDAY',
            });
        } else if (!selectedDays.has(weekday)) {
            documentRows.push({
                key: `special-${workDate}`,
                kind: 'offday',
                day_number: cursor.date(),
                label: cursor.format('dddd').toUpperCase(),
            });
        } else {
            documentRows.push({
                key: `work-${workDate}`,
                kind: 'work',
                day_number: cursor.date(),
                task_values: rows.map((task) => ({
                    sort_order: task.sort_order,
                    task_type: task.task_type,
                    cell: task.daily_values.find((value) => value.work_date === workDate) ?? {
                        work_date: workDate,
                        numeric_value: 0,
                        mark_value: 'dash',
                    },
                })),
            });
        }

        cursor = cursor.add(1, 'day');
    }

    return documentRows;
}

function persistCountableRangeSettings() {
    const storageKey = getCountableRangeStorageKey();

    if (!storageKey || typeof window === 'undefined') return;

    const payload = taskRows.value.reduce((carry, row) => {
        carry[row.sort_order] = {
            min: row.auto_min,
            max: row.auto_max,
        };

        return carry;
    }, {});

    window.localStorage.setItem(storageKey, JSON.stringify(payload));
}

function getCountableRangeStorageKey() {
    if (!props.subject) return null;

    const subjectKey = props.subject.id
        ?? props.subject.employee_id
        ?? props.subject.employee_no
        ?? props.subject.display_name
        ?? 'subject';

    return `swa:countable-range:${props.moduleType}:${subjectKey}`;
}

function savedReportEndpoint(reportId) {
    if (props.moduleType === 'personal') {
        return `/api/swa/personal/reports/${reportId}`;
    }

    return `/api/swa/employees/${props.subject?.id}/reports/${reportId}`;
}

function isCountableRangeInvalid(row) {
    if (row.task_type !== 'countable') return false;

    return !Number.isFinite(row.auto_min)
        || !Number.isFinite(row.auto_max)
        || row.auto_min < 0
        || row.auto_max < row.auto_min;
}

function resolveCountableRange(row) {
    const min = normalizeStoredRangeValue(row.auto_min, DEFAULT_COUNTABLE_MIN);
    const max = normalizeStoredRangeValue(row.auto_max, DEFAULT_COUNTABLE_MAX);

    return {
        min,
        max: Math.max(min, max),
    };
}

function formatDateForApi(value) {
    return value ? dayjs(value).format('YYYY-MM-DD') : '';
}

function formatShortDate(value) {
    return dayjs(value).format('MMM D');
}

function formatWeekdayLabel(value) {
    return dayjs(value).format('ddd').toUpperCase();
}

function formatSwaPeriodLabel(startValue, endValue) {
    if (!startValue || !endValue) return '—';

    const start = dayjs(startValue);
    const end = dayjs(endValue);

    if (!start.isValid() || !end.isValid()) return '—';

    if (start.year() === end.year()) {
        if (start.month() === end.month()) {
            return `${start.format('MMMM').toUpperCase()} ${start.date()}-${end.date()}, ${end.format('YYYY')}`;
        }

        return `${start.format('MMMM').toUpperCase()} ${start.date()}-${end.format('MMMM').toUpperCase()} ${end.date()}, ${end.format('YYYY')}`;
    }

    return `${start.format('MMMM').toUpperCase()} ${start.date()}, ${start.format('YYYY')} - ${end.format('MMMM').toUpperCase()} ${end.date()}, ${end.format('YYYY')}`;
}

function formatUpperText(value) {
    const text = String(value ?? '').trim();
    return text ? text.toUpperCase() : '';
}

function formatUpperList(values) {
    return (Array.isArray(values) ? values : [])
        .map((value) => formatUpperText(value))
        .filter(Boolean);
}

function formatTaskType(value) {
    return value === 'check_blank' ? 'Check / Blank (-)' : 'Countable';
}

function formatDayLabel(value) {
    const match = weekdayOptions.find((option) => option.value === value);
    return match?.label ?? value;
}

function formatReportRange(report) {
    return `${dayjs(report.period_start_date).format('MMM D, YYYY')} - ${dayjs(report.period_end_date).format('MMM D, YYYY')}`;
}

function formatCreatedAt(value) {
    return value ? dayjs(value).format('MMM D, YYYY h:mm A') : 'Saved';
}

function randomCountableValue(row) {
    const { min, max } = resolveCountableRange(row);

    return Math.floor(Math.random() * (max - min + 1)) + min;
}

function randomMarkValue() {
    return Math.random() >= 0.35 ? 'check' : 'dash';
}
</script>